"""The transcript is rendered from what the seats said, not rewritten by the chair.

Measured over 20 completed deliberations: the chair's output is ~1,916 tokens,
of which the `transcript` field is 5,811 characters — roughly 1,450 tokens, 76%
of everything the chair produces. It was being asked to write out the seat
opinions it had just been handed.

Two problems, and the second is the reason to change it even if tokens were free.

COST. Output is the dominant term on this model, and the transcript is ~27% of
the output of an entire deliberation. At the overnight burn rate that is real
money spent regenerating text we already hold.

TRUTH. A transcript regenerated by a model is a PARAPHRASE presented as a
record. Nothing constrains the chair to quote the seats accurately, and a
"transcript" that drifts from what was actually said is worse than no transcript
— it is a misleading artefact stored alongside the opinions it misquotes.

`_render_opinions` already produces this deterministically from the stored
opinions, and the fallback path has always used it. The LLM path now does too.
"""

import pytest

from roundtable.engine import RoundTable
from roundtable.types import SeatOpinion


def _op(seat, signal, reasoning):
    return SeatOpinion(seat_id=seat, seat_name=seat.title(), signal=signal,
                       confidence=55.0, reasoning=reasoning)


def test_the_chair_is_no_longer_asked_for_a_transcript():
    """The schema it is given must not request the field, or it will spend
    tokens producing one whatever we do with the answer."""
    from roundtable.seats import CHAIR_SYSTEM_PROMPT
    assert '"transcript"' not in CHAIR_SYSTEM_PROMPT


def test_the_transcript_is_rendered_from_the_actual_opinions():
    table = RoundTable(client=None)
    ops = [_op("quant", "bullish", "momentum is real"),
           _op("risk", "neutral", "stop sits on the floor")]
    rendered = table._render_opinions(ops)
    assert "momentum is real" in rendered
    assert "stop sits on the floor" in rendered
    assert "Quant" in rendered and "Risk" in rendered


def test_every_seat_that_spoke_appears():
    """A record that drops a seat is not a record. The chair had no obligation
    to include them all; this does."""
    table = RoundTable(client=None)
    ops = [_op(s, "neutral", f"{s} said something") for s in
           ("quant", "risk", "sentiment", "corroborator", "devils_advocate")]
    rendered = table._render_opinions(ops)
    for s in ("Quant", "Risk", "Sentiment", "Corroborator", "Devils_Advocate"):
        assert s in rendered, s


def test_an_abstention_is_shown_as_one():
    table = RoundTable(client=None)
    failed = SeatOpinion(seat_id="quant", seat_name="Quant", signal="neutral",
                         confidence=0.0, reasoning="", failed=True,
                         error="api down")
    assert "ABSTAINED" in table._render_opinions([failed])


def test_the_stored_consensus_carries_the_rendered_transcript():
    """End to end: what lands in the payload is the deterministic rendering."""
    import asyncio

    from roundtable.types import Candidate, Thesis

    class _Client:
        def __init__(self): self.calls = []
        def messages_create(self, **kw): raise NotImplementedError

    table = RoundTable(client=None)
    thesis = Thesis(thesis_id="t", symbol="BTC-USD", asset_class="crypto")
    thesis.opinions = [_op("quant", "bullish", "a distinctive phrase here")]
    consensus = table._fallback_consensus(thesis, "test")
    assert "a distinctive phrase here" in consensus.transcript
